# Test your FastAPI endpoints

POST http://localhost:8000/run
Content-Type: application/json

{
  "illegal_words": [
    "تفنگ",
     "سیر",
     "سیرجان",
     "بی ادب",
     "بی‌تربیت"
  ],
  "text" : "سلام الاغ عزیز، حالت چطوره؟ خوب و خوش و سلامتی، بارت چطوره؟"
}
###

# test runpdf endpoint

POST http://localhost:8000/runpdf
Content-Type: application/json

{
  "illegal_words": [
    "تفنگ",
     "سیر",
     "سیرجان",
     "بی ادب",
     "بی‌تربیت"
  ],
  "pdf" : "test.pdf"
}
###
